name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.5+1
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.12.0
  auto_size_text: ^3.0.0
  visibility_detector: ^0.4.0+2
  fl_chart: ^1.1.1
  flutter_tts: ^4.2.3
  file_picker: ^10.3.6
  speech_to_text: ^7.3.0
  flutter_neumorphic_plus: ^3.5.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.10
  share_plus: ^12.0.1
  animated_text_kit: ^4.3.0
  intl_phone_field: ^3.2.0
  firebase_performance: ^0.11.1+2
  google_generative_ai: ^0.4.7
  google_sign_in: ^6.2.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  shared_preferences: ^2.5.3
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  timeline_tile: ^2.0.0
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  http: ^1.6.0
  url_launcher: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.13
  uuid: ^4.4.0
  timezone: ^0.10.1
  flutter_svg: ^2.2.2
  permission_handler: ^12.0.1
  mime: ^2.0.0
  dropdown_search: ^5.0.6
  printing: ^5.14.2
  flutter_localizations:
    sdk: flutter
  firebase_ai: ^3.6.0
  just_audio: ^0.10.5
  webfeed_plus: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1

dependency_overrides:
  intl: ^0.20.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - GEMINI.md
